version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo -----PREBUILD-----
      - npm install
  pre_build:
    commands:
      - echo -----PREBUILD-----
      - npm run prebuild
  build:
    commands:
      - echo -----BUILD-----
      - npm run build
  post_build:
    commands: 
      - echo -----POSTBUILD-----
      - echo Build completed on `date`
artifacts:
  discard-paths: yes
  files:
    - src/*

