version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo -----PHASE INSTALL-----
      - export SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id user/liam/nexusAuthToken --query SecretString --output text)
      - echo "$SECRET_VALUE" > .npmrc
      - npm install
  pre_build:
    commands:
      - echo -----PHASE PREBUILD-----
  build:
    commands:
      - echo -----PHASE BUILD-----
      - npm run build
  post_build:
    commands: 
      - echo -----PHASE POSTBUILD-----
      - echo Build completed on `date`
artifacts:
  discard-paths: yes
  files:
    - src/*

