version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - npm run prebuild
      - echo "hi"
  post_build:
    commands: 
      - echo Build completed on `date`
artifacts:
  discard-paths: yes
  files:
    - src/*

