version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - npm run prebuild
      - echo "hi"
artifacts:
  files:
    - src/*
  base-directory: dist/
