version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo -----PHASE INSTALL-----
      - npm install
  pre_build:
    commands:
      - echo -----PHASE PREBUILD-----
  build:
    commands:
      - echo -----PHASE BUILD-----
      - npm run build
  post_build:
    commands: 
      - echo -----PHASE POSTBUILD-----
      - echo Build completed on `date`
artifacts:
  discard-paths: yes
  files:
    - src/*

