version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - npm run prebuild
      - echo "hi"
  postbuild:
    commands: 
      - aws codebuild update-project --name <project-name> --source-version <source-version> --artifacts "type": "CODEPIPELINE"  
artifacts:
  files:
    - src/*
  base-directory: dist/
